import { StyleSheet } from "@react-pdf/renderer";

export const pdfColors = {
  orange: "#ea580c",
  orangeLight: "#fed7aa",
  green: "#15803d",
  greenLight: "#bbf7d0",
  slate950: "#020617",
  slate900: "#0f172a",
  slate800: "#1e293b",
  slate700: "#334155",
  slate600: "#475569",
  slate500: "#64748b",
  slate300: "#cbd5e1",
  white: "#ffffff",
};

export const pdfStyles = StyleSheet.create({
  page: {
    backgroundColor: pdfColors.white,
    color: pdfColors.slate900,
    flexDirection: "column",
    fontFamily: "Helvetica",
    paddingBottom: 22,
    paddingHorizontal: 40,
    paddingTop: 30,
  },
  content: {
    flexDirection: "row",
    flexGrow: 1,
  },
  leftColumn: {
    flexBasis: "50%",
    paddingRight: 20,
  },
  rightColumn: {
    flexBasis: "50%",
    paddingLeft: 20,
  },
  eyebrow: {
    color: pdfColors.orange,
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: 2.5,
    textTransform: "uppercase",
  },
  header: {
    borderBottomColor: pdfColors.orangeLight,
    borderBottomWidth: 1,
    paddingBottom: 18,
  },
  title: {
    color: pdfColors.slate950,
    fontSize: 27,
    fontWeight: 700,
    lineHeight: 1.1,
    marginTop: 12,
  },
  subtitle: {
    color: pdfColors.slate600,
    fontSize: 11.5,
    lineHeight: 1.25,
    marginTop: 12,
  },
  customer: {
    color: pdfColors.slate500,
    fontSize: 10,
    fontWeight: 500,
    marginTop: 16,
  },
  summary: {
    marginTop: 24,
  },
  section: {
    marginBottom: 16,
  },
  advantageSection: {
    borderBottomColor: pdfColors.orangeLight,
    borderBottomWidth: 1,
    marginBottom: 16,
    paddingBottom: 16,
  },
  centeredText: {
    textAlign: "center",
  },
  advantageValue: {
    color: pdfColors.green,
    fontSize: 30,
    fontWeight: 700,
    marginTop: 8,
  },
  advantageText: {
    color: pdfColors.slate600,
    fontSize: 10,
    lineHeight: 1.25,
    marginTop: 8,
  },
  summaryRows: {
    marginTop: 8,
  },
  summaryRow: {
    flexDirection: "row",
    fontSize: 10,
    fontWeight: 500,
    justifyContent: "space-between",
    lineHeight: 1.25,
    paddingVertical: 2,
  },
  summaryLabel: {
    color: pdfColors.slate800,
  },
  summaryValue: {
    color: pdfColors.slate800,
    textAlign: "right",
    width: 90,
  },
  sumRow: {
    borderTopColor: pdfColors.slate950,
    borderTopWidth: 1.5,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
    paddingTop: 6,
  },
  sumLabel: {
    color: pdfColors.slate950,
    fontSize: 11,
    fontWeight: 700,
  },
  sumValue: {
    color: pdfColors.slate950,
    fontSize: 13,
    fontWeight: 700,
  },
  periodRow: {
    color: pdfColors.slate950,
    flexDirection: "row",
    fontSize: 11,
    fontWeight: 700,
    justifyContent: "space-between",
    lineHeight: 1.25,
    marginTop: 5,
  },
  periodValue: {
    color: "#dc2626",
    fontFamily: "Helvetica",
    fontSize: 13,
    fontWeight: 700,
    lineHeight: 1,
    textAlign: "right",
    width: 90,
  },
  calculationsHeader: {
    marginBottom: 10,
  },
  calculationsTitle: {
    color: pdfColors.slate950,
    fontSize: 10.5,
    fontWeight: 700,
    marginTop: 7,
  },
  card: {
    borderTopColor: pdfColors.orangeLight,
    borderTopWidth: 1.5,
    marginBottom: 24,
    paddingTop: 8,
  },
  cardTitle: {
    color: pdfColors.slate950,
    fontSize: 12,
    fontWeight: 700,
    marginBottom: 5,
  },
  protocolRow: {
    flexDirection: "row",
    fontSize: 8,
    lineHeight: 1.25,
    paddingVertical: 1,
  },
  protocolLabel: {
    color: pdfColors.slate600,
    width: 95,
  },
  protocolFormula: {
    color: pdfColors.slate800,
    fontWeight: 500,
    width: 182,
  },
  protocolAmount: {
    color: pdfColors.slate900,
    fontWeight: 700,
    textAlign: "right",
    width: 73,
  },
  totalArea: {
    borderTopColor: pdfColors.slate300,
    borderTopWidth: 1,
    marginTop: 6,
    paddingTop: 5,
  },
  strongLabel: {
    color: pdfColors.slate950,
    fontWeight: 700,
  },
  strongFormula: {
    color: pdfColors.slate950,
    fontWeight: 700,
  },
  savingsBar: {
    borderBottomColor: pdfColors.greenLight,
    borderBottomWidth: 1,
    borderTopColor: pdfColors.greenLight,
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 5,
    paddingVertical: 5,
  },
  savingsLabel: {
    color: pdfColors.green,
    fontSize: 10,
    fontWeight: 700,
    marginRight: 30,
  },
  savingsValue: {
    color: pdfColors.green,
    fontSize: 11,
    fontWeight: 700,
  },
  footer: {
    borderTopColor: pdfColors.orangeLight,
    borderTopWidth: 1,
    color: pdfColors.slate500,
    fontSize: 8,
    fontWeight: 500,
    marginTop: 10,
    paddingTop: 8,
    textAlign: "center",
  },
});
